name: Schedule meetings
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pkgjs/meet@v0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: '2020-10-09T17:00:00.0Z/P14D'
        issueTitle: 'Conventional Commits Steering Meeting <%= date.toFormat("yyyy-MM-dd") %>'
        agendaLabel: 'tsc-agenda'
